# Tasks to install and configure MariaDB
---
- name: Install MariaDB
  block:
    - name: Install MariaDB package
      dnf:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: present
  rescue:
    - name: Print error if MariaDB installation fails
      debug:
        msg: "Failed to install MariaDB. Please check the package manager."

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Check if MySQL root can connect without password
  command: mysql -u root -e "SELECT 1"
  register: mysql_root_check
  ignore_errors: yes
  changed_when: false

- name: Set MySQL root password
  command: mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('secure_password_123');"
  when: mysql_root_check.rc == 0
  register: root_password_set
  changed_when: true

- name: Update root authentication to mysql_native_password
  command: mysql -u root -p'secure_password_123' -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password;"
  when: root_password_set is success
  changed_when: true

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "secure_password_123"
  when: root_password_set is success

- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "secure_password_123"
  when: root_password_set is success