# Tasks to install and configure MariaDB
---
- name: Install MariaDB
  block:
    - name: Install MariaDB package
      dnf:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: present
  rescue:
    - name: Print error if MariaDB installation fails
      debug:
        msg: "Failed to install MariaDB. Please check the package manager."

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Check if MySQL root password is set
  command: mysqladmin -u root ping
  register: mysql_ping
  ignore_errors: yes

- name: Secure MariaDB installation
  command: mysql_secure_installation
  when: mysql_ping.rc == 0
  environment:
    MYSQL_ROOT_PASSWORD: "secure_password_123"
  changed_when: true
  ignore_errors: yes

- name: Set MySQL root password
  mysql_user:
    name: root
    host: localhost
    password: "secure_password_123"
    login_user: root
    login_password: "{{ mysql_root_password | default('') }}"
    state: present
  vars:
    mysql_root_password: "{{ 'secure_password_123' if mysql_ping.rc != 0 else '' }}"
  ignore_errors: yes