# Tasks to install and configure MariaDB
---
- name: Install MariaDB
  block:
    - name: Install MariaDB package
      dnf:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: present
  rescue:
    - name: Print error if MariaDB installation fails
      debug:
        msg: "Failed to install MariaDB. Please check the package manager."

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Check if MySQL root can connect without password
  command: mysql -u root -e "SELECT 1"
  register: mysql_root_check
  ignore_errors: yes
  changed_when: false

- name: Set MySQL root password and authentication
  mysql_user:
    name: root
    host: localhost
    password: "secure_password_123"
    plugin: mysql_native_password
    login_user: root
    login_password: ""
    state: present
  when: mysql_root_check.rc == 0
  register: root_setup

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "secure_password_123"
  when: root_setup is success

- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "secure_password_123"
  when: root_setup is success